apiVersion: v1
kind: Secret
metadata:
  name: codecommit-credentials
  namespace: apps-build
type: Opaque
stringData:
  username: {{ .Values.pipelines.codeRepo.username }}
  password: {{ .Values.pipelines.codeRepo.password }}